apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gonzaloaune@stakwork.com
    privateKeySecretRef:
      name: letsencrypt-dns01-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        route53:
          region: ${AWS_REGION}
          hostedZoneID: ${AWS_HOSTED_ZONE_ID}
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
          accessKeyIDSecretRef:
            name: route53-credentials
            key: access-key-id
          
