apiVersion: v1
kind: Service
metadata:
  name: workspace-controller
  namespace: workspace-system
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: workspace-controller