---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-cert-creator
  namespace: workspace-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-cert-creator
  namespace: workspace-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-cert-creator
  namespace: workspace-system
subjects:
- kind: ServiceAccount
  name: registry-cert-creator
  namespace: workspace-system
roleRef:
  kind: Role
  name: registry-cert-creator
  apiGroup: rbac.authorization.k8s.io