apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-config
  namespace: workspace-system
data:
  # AWS settings (FIXED)
  awsRegion: ${AWS_REGION}
  awsAccessKeyId: ${AWS_ACCESS_KEY_ID}
  awsSecretKey: ${AWS_SECRET_ACCESS_KEY}

  # Cluster settings (FIXED)
  clusterRegion: ${AWS_REGION}

  # Domain settings (FIXED)
  domain: ${REPLACE_ME}
  subdomain: ${SUBDOMAIN}
  parentDomain: ${REPLACE_ME}
  workspaceDomain: ${SUBDOMAIN_REPLACE_ME}
  workspaceDomainZoneId: ${AWS_HOSTED_ZONE_ID}

  # Service account (FIXED)
  serviceAccountAnnotations: |
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/workspace-controller-role

  # Namespaces (FIXED)
  workspaceNamespace: ${WORKSPACE_NAMESPACE}

  # Pod network (FIXED)
  podName: ${POD_NAME}
  podNamespace: ${POD_NAMESPACE}
  podIP: ${POD_IP}
  podServiceAccount: ${POD_SERVICE_ACCOUNT}

  # Container settings (FIXED)
  containerName: ${CONTAINER_NAME}
  containers: ${CONTAINERS}
  containerPorts: ${CURRENT_PORTS}

  # Code server settings (FIXED)
  codeServerContainer: ${CODE_SERVER_CONTAINER}
  codeServerPort: ${PORT}
  currentPorts: ${CURRENT_PORTS}

  # CM Data (FIXED)
  cmName: ${CM_NAME}
  cmData: ${CM_DATA}
  newCmData: ${NEW_CM_DATA}

  # Certificates (FIXED)
  certsExist: ${CERTS_EXIST}

  # Ingress settings (FIXED)
  ingressExist: ${INGRESS_EXIST}
  ingressPort: ${PORT}


