apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-config
  namespace: workspace-system
data:
  # AWS settings (FIXED)
  awsRegion: "${AWS_REGION}"
  awsAccessKeyId: "${AWS_ACCESS_KEY_ID}"
  awsSecretKey: "${AWS_SECRET_ACCESS_KEY}"

  # Cluster settings (FIXED)
  clusterRegion: "${AWS_REGION}"

  # Domain settings (FIXED)
  domain: "${REPLACE_ME}"
  parentDomain: "${REPLACE_ME}"
  workspaceDomain: "${SUBDOMAIN_REPLACE_ME}"
  workspaceDomainZoneId: "${AWS_HOSTED_ZONE_ID}"

  # Service account (FIXED)
  serviceAccountAnnotations: |
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/workspace-controller-role