apiVersion: v1
kind: Secret
metadata:
  name: workspace-secrets
  namespace: workspace-system
type: Opaque
stringData:
  # AWS credentials
  awsAccountId: ${AWS_ACCOUNT_ID}
  awsRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/workspace-controller-role
  awsAccessKey: ${AWS_ACCESS_KEY_ID}
  awsSecretKey: ${AWS_SECRET_ACCESS_KEY}
  awsRegion: ${AWS_REGION}

  # Domain settings
  domain: ${REPLACE_ME}
  parentDomain: ${REPLACE_ME}
  workspaceDomain: ${SUBDOMAIN_REPLACE_ME}
  domainZoneId: ${AWS_HOSTED_ZONE_ID}
  workspaceDomainZoneId: ${AWS_HOSTED_ZONE_ID}

  # Cluster settings
  clusterRegion: ${AWS_REGION}

  # Service account
  serviceAccountAnnotations: |
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/workspace-controller-role

  # Namespaces
  workspaceNamespace: ${WORKSPACE_NAMESPACE}

  # Pod network
  podName: ${POD_NAME}
  podNamespace: ${POD_NAMESPACE}
  podIP: ${POD_IP}
  podServiceAccount: ${POD_SERVICE_ACCOUNT}

  # Container settings
  containerName: ${CONTAINER_NAME}
  containers: ${CONTAINERS}

  # Code server settings
  codeServerContainer: ${CODE_SERVER_CONTAINER}

  # ConfigMap Data
  cmName: ${CM_NAME}
  cmData: ${CM_DATA}
  newCmData: ${NEW_CM_DATA}

  # Certificates
  certsExist: ${CERTS_EXIST}

  # Ingress settings
  ingressExist: ${INGRESS_EXIST}
