apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-controller
  namespace: workspace-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxyyyzzz:role/workspace-controller-role

