apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-admin
  namespace: workspace-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-admin
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-admin
subjects:
- kind: ServiceAccount
  name: registry-admin
  namespace: workspace-system
roleRef:
  kind: ClusterRole
  name: registry-admin
  apiGroup: rbac.authorization.k8s.io
